version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "eslint"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "eslint-config-prettie"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "eslint-plugin-prettier"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "lint-staged"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "np"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "prettier"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "husky"
